# Generated by Django 2.2.1 on 2019-05-25 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('BH1 Supervisor', 'BH1 Supervisor'), ('BH1 Warden', 'BH1 Warden'),
                                            ('BH1 Assistant Warden', 'BH1 Assistant Warden'),
                                            ('BH2 Supervisor', 'BH2 Supervisor'), ('BH2 Warden', 'BH2 Warden'),
                                            ('BH2 Assistant Warden', 'BH2 Assistant Warden'),
                                            ('BH3 Supervisor', 'BH3 Supervisor'), ('BH3 Warden', 'BH3 Warden'),
                                            ('BH3 Assistant Warden', 'BH3 Assistant Warden'),
                                            ('GH Supervisor', 'GH Supervisor'), ('GH Warden', 'GH Warden'),
                                            ('GH Assistant Warden', 'GH Assistant Warden'),
                                            ('Control Room', 'Control Room'), ('Student', 'Student')],
                                   default='Student', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hostel',
            field=models.CharField(choices=[('BH1', 'BH1'), ('BH2', 'BH2'), ('BH3', 'BH3'), ('GH', 'GH')],
                                   default='BH1', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mob_no',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='room_no',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
