# Generated by Django 2.1.7 on 2019-05-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20190528_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hostel',
            field=models.CharField(
                choices=[('BH1(Arawali Hostel)', 'BH1(Arawali Hostel)'), ('BH2(Nilgiri Hostel)', 'BH2(Nilgiri Hostel)'),
                         ('BH3(Shivalik Hostel)', 'BH3(Shivalik Hostel)'),
                         ('GH(Gangotri Hostel)', 'GH(Gangotri Hostel)')], default='BH1', max_length=30),
        ),
    ]
