# Generated by Django 2.1.7 on 2019-05-28 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gatepass_apply', '0003_auto_20190528_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='applied_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='from_date',
            field=models.CharField(default=datetime.datetime(2019, 5, 28, 23, 26, 28, 494506), max_length=30),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='to_date',
            field=models.CharField(default=datetime.datetime(2019, 5, 28, 23, 26, 28, 494506), max_length=30),
        ),
    ]
