# Generated by Django 2.1.7 on 2019-05-30 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gatepass_apply', '0004_auto_20190528_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='from_date',
            field=models.CharField(default=datetime.datetime(2019, 5, 30, 18, 32, 38, 386695), max_length=30),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='to_date',
            field=models.CharField(default=datetime.datetime(2019, 5, 30, 18, 32, 38, 386695), max_length=30),
        ),
    ]
