# Generated by Django 2.1.7 on 2019-06-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gatepass_apply', '0006_auto_20190612_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='from_date',
            field=models.CharField(default='From', max_length=30),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='to_date',
            field=models.CharField(default='To', max_length=30),
        ),
    ]
